export const PRODUCT_CATALOG_ACTION_TYPES = {
  "FETCH_CATEGORIES_START": "FETCH_CATEGORIES_START",
  "FETCH_CATEGORIES_SUCCESS": "FETCH_CATEGORIES_SUCCESS",
  "FETCH_CATEGORIES_FAILED": "FETCH_CATEGORIES_FAILED",
}
